### PR TITLE
cmd: give 'helpful' hint about --rootless

### PR DESCRIPTION
**Pull request by cyphar**
We still need to massively reduce the amount of dumb output we are
spewing out. Logrus is both a blessing and a curse.

Reported-by: Antonio Murdaca <runcom@redhat.com>
Signed-off-by: Aleksa Sarai <asarai@suse.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Is this hint good enough for now @runc0m? I'm going to and up switching the logging to be less insane soon.

**Comment by runcom** [comment]
Sounds good to me, thanks!

**Comment by cyphar** [comment]
LGTM. Cheers!

**Comment by cyphar** [comment]
Closes #58

**Pull request merged**
