### PR TITLE
Use correct flag for host networking

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
This PR removes the post opencontainers/runtime-tools#288 flag and
replaces it with a current-runtime-tools flag.  I'm not sure what the
timescale is for opencontainers/runtime-tools#288, but it sounds like
folks are generally in favor of the flag that this PR is removing.

**Comment by mrunalp** [comment]
@wking Yeah, could just wait for that one.

**Comment by cyphar** [comment]
Yeah I wrote the README while making opencontainers/runtime-tools#288. I don't really mind either way TBH.

**Comment by cyphar** [comment]
@mrunalp Thanks for reminding me to check opencontainers/runtime-tools#288. :wink:

**Comment by cyphar** [comment]
opencontainers/runtime-tools#288 has been merged, so this is no longer necessary. Thanks anyway @mrunalp! :smile_cat:

**Pull request closed without merging**
